### ISSUE TITLE
[META] User testing 1

### ISSUE THREAD

**Issue by Pryx** [Pryx/git-md-diff#56]
User testing problems - part of #29 

Screener: TODO

High priority
- [x] Cursor does not indicate a documentation is clickable
- [x] If we delete slug while creating a new Docu, new one is not generated
- [x] Empty user added to documentation causes error
- [x] Cannot easily tell which one is earlier commit
- [x] Proofreading request - warning alert "Merge not yet possible" confusing when shown right after creating the request.
- [x] Buttons not hiding when merged/submitted changes
- [x] State of the request should be more easily distinguishable
- [x] Proofreading request description - not sure what it means, where is displayed
- [x] Merged request causes error on refresh
- [x] Back button should be added, fear of undoing changes otherwise
- [x] Allow switching "My changes" and "Diff changes" in proofreading

Medium priority
- [x] No invisible changes is confusing
- [ ] Link to users GitLab account

Low priority
- [ ] Indicate a folder has editable elements (might not be possible at this time)

**Comment by Pryx** [comment]
All priority changes done
