### ISSUE TITLE
[META] User testing 2

### ISSUE THREAD

**Issue by Pryx** [Pryx/git-md-diff#59]
User testing problems - part of #29 

This testing is WIP, didn't have enough time and encountered many problems in the first run

Screener: TODO

High priority
- [x] We should be able to write commit message
- [x] Files sometimes do not load
- [x] Login not working (not sure why and couldn't access logs on CodeNow, maybe temporary GitLab error?) - Login was github error - see #60 
- [x] Commits not limited - not easily distinguishable how to select diff range
- [x] We should have some info about the user levels present
- [x] If file didn't change, do not allow saving
- [x] Revisions do not load sometimes - gitlab is slow to respond
- [x] We should inform the proofreader that he cannot make any more changes after submitting
- [x] Files should be "hidden" by default, only showing diff when needed. Could actually use this to defer rendering
- [x] Edit button should be present, not only clickable title
- [x] Proofreader should see differences by default, not "Preview". Name of the differences card could be "Highlighted changes" or something more clear to non-technical people.
- [x] We shouldn't allow user to navigate away from the editor if changes were made.
- [x] Badge tooltips - we should explain what each badge means. Also they should be present at the top rather than at the bottom.
- [x] When switching branches hash is present rather than date and time in commit  select
- [x] Merge - button should be disabled while waiting for server response
- [x] We should send out emails when user is added / proofreading req. state changed

Medium priority
- [x] Start typing when searching user might not be clear
- [x] Select all files / deselect all files
- [ ] Duplicate file - useful so that we don't have to start from a blank file.
- [ ] Breadcrumbs should have documentation & proofreading req. name, not ID
- [ ] Detect whether branch is protected and we don't have access
- [ ] State of tabs is not saved on reload

Low priority
- [ ] Internal links should work
- [ ] Mark as complete button could be Proofreading finished
- [ ] Autosave diff would be nice to have
- [ ] New file - is the green color correct?
