### ISSUE TITLE
[META] User testing 3

### ISSUE THREAD

**Issue by Pryx** [Pryx/git-md-diff#61]
User testing problems - part of #29 

Screener: TODO

High priority
- [x] User ID is confusing (Settings)
- [x] Why some files cannot be opened? Maybe allow downloading them?
- [x] An error is not shown when file save failed
- [x] Proofreading requests and documentations cause commit selects to act weird
- [x] Specify what extension do new pages have
- [x] Commit message in commit select is too short (when dropdown closed)
- [x] "NEW" file badge is confusing
- [x] Errors when creating file/folder not shown properly
- [x] Proofreading request should include contact for the proofreader & requester
- [x] Missing breadcrumbs in proofreaders view
- [x] Check whitespace only titles
- [x] Unknown email - explanation
- [x] Highlight required fields
- [x] Access levels should be described
- [x] Make it possible to change user level without deleting the user

Medium priority
- [ ] A documentation should be available to describe functions
- [ ] Some elements change position when alert disappears
- [ ] Proofreading requests should contain information about which docu they belong to
- [x] Author should be before the commit message
- [ ] User can be added twice (selectbox search)

Low priority
- [ ] Search requires diacritics (might be wontfix, because it's dependend on Gitlab API)
